[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mlflow>=2.17.2",
    "scikit-learn>=1.5.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
