experiment_name: training

bucket_name: elt-data
training_data_folder: rest_api_data/air_quality/

features:
  - carbon_monoxide
  - nitrogen_dioxide
  - sulphur_dioxide
  - ozone
  - dust
  - european_aqi

estimator_params:
  n_estimators: 400
  min_samples_split: 2
