data_filepath: data
target_column: MedHouseVal
estimator_params:
  hidden_layer_sizes: [10, 20, 15]
  alpha: 0.01
  max_iter: 10

mlflow_uri: http://127.0.0.1:5000
experiment_name: housing

bucket_name: elt_data
training_data: rest_api_data/air_quality/2024-11-14/1731606441.4002414.0d885de67b.csv
