[project]
name = "elt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[duckdb,filesystem]>=1.3.0",
    "prefect>=3.1.2",
    "streamlit>=1.40.1",
]
