[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "streamlit>=1.39.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
